# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NOrLrZwnA5YKZs34hQZVRA8fidsSP1Wf
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from google.colab import files
files.upload()

import os
import zipfile

# Create the .kaggle folder
os.makedirs("/root/.kaggle", exist_ok=True)

# Move kaggle.json to that folder
!mv kaggle.json /root/.kaggle/

# Set permissions
!chmod 600 /root/.kaggle/kaggle.json

!pip install -q kaggle

# Download the dataset
!kaggle datasets download -d joniarroba/noshowappointments

# Unzip the downloaded file
with zipfile.ZipFile("noshowappointments.zip", 'r') as zip_ref:
    zip_ref.extractall("noshowappointments")

import pandas as pd

# Load the CSV file
data = pd.read_csv("noshowappointments/KaggleV2-May-2016.csv")

# Preview
data.head()

data.duplicated().sum()

data.PatientId.nunique()

data.PatientId.duplicated().sum()

data.duplicated(['PatientId', 'No-show']).sum()

data.info()

data.describe()

data['Age'].describe()

mask = data[data['Age'] == -1]
print(mask)

data.drop(index=99832, inplace=True)

data.Age.describe()

data.drop_duplicates(['PatientId', 'No-show'], inplace=True)

data.drop(['PatientId', 'AppointmentID', 'ScheduledDay', 'AppointmentDay'], axis=1, inplace=True)

data



